#!/usr/bin/env sh

#
# for this to work you must configure sudo such that
# it will be able to run the command without password
#
# see this wiki page for information:
#  - https://github.com/asmvik/yabai/wiki/Installing-yabai-(latest-release)#configure-scripting-addition
#
# yabai signal add dock-did-restart --label load-scripting-addition --action "sudo yabai scripting-addition load"
# sudo yabai scripting-addition load
#

# global settings
yabai config set                                    \
    --external-bar                 off:40:0         \
    --menubar-opacity              1.0              \
    --mouse-follows-focus          off              \
    --focus-follows-mouse          off              \
    --display-arrangement-order    default          \
    --window-origin-display        default          \
    --window-placement             second-child     \
    --window-insertion-point       focused          \
    --window-zoom-persist          on               \
    --window-shadow                on               \
    --skip-window-focus-animation  off              \
    --window-animation-duration    0.0              \
    --window-animation-easing      ease-out-circ    \
    --window-opacity-duration      0.0              \
    --active-window-opacity        1.0              \
    --normal-window-opacity        0.90             \
    --window-opacity               off              \
    --insert-feedback-color        0xffd75f5f       \
    --split-ratio                  0.50             \
    --split-type                   auto             \
    --auto-balance                 off              \
    --top-padding                  12               \
    --bottom-padding               12               \
    --left-padding                 12               \
    --right-padding                12               \
    --window-gap                   6                \
    --layout                       bsp              \
    --mouse-modifier               fn               \
    --mouse-action1                move             \
    --mouse-action2                resize           \
    --mouse-drop-action            swap

echo "yabai configuration loaded.."
